# Generated by Django 4.2.7 on 2024-01-17 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('TR', 'Trincomalee'), ('BT', 'Batticaloa'), ('AR', 'Ampara'), ('JF', 'Jaffna'), ('VU', 'Vavuniya'), ('MR', 'Mannar'), ('MU', 'Mullaitheevu'), ('KL', 'Kilinochchi'), ('NE', 'Nuwara-Eliya'), ('KY', 'Kandy'), ('BL', 'Badullah'), ('MA', 'Monaragala'), ('KE', 'Kegalle'), ('RN', 'Ratnapura'), ('CO', 'Colombo'), ('ME', 'Matale'), ('GM', 'Gampaha'), ('KA', 'Kaluthara'), ('MT', 'Matara'), ('GE', 'Galle'), ('HM', 'Hambantota'), ('AR', 'Anuradhapura'), ('KU', 'Kurunegala'), ('PO', 'Polonaruwa'), ('PM', 'Puttalam')], max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
